<a href="https://colab.research.google.com/github/wyjun1988/financeStudy/blob/develop/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [2]:
import numpy as np

In [ ]:
ar = np.array([0,1,2])

In [ ]:
ar

array([0, 1, 2])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
data = [0, 1, 2, 3]
x= np.array(data)
print(2*x)
x = list(map(lambda x:2*x, data))
print(x)

[0 2 4 6]
[0, 2, 4, 6]


## 2D array

In [ ]:
c = np.array([[0,1,2],[3,4,5]]) # 2x3 array
len(c)
len(c[0])

3

## 3D array


In [ ]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [ ]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [ ]:
print(d.ndim)

3


In [ ]:
print(d.shape)

(2, 3, 4)


In [ ]:
d[0,1,2]

7

In [ ]:
d[0,1,:]

array([5, 6, 7, 8])

In [ ]:
d[:,1,2]

array([ 7, 17])

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [ ]:
x = np.array([1,2,3])

# data type

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [ ]:
x

array([1., 2., 3.], dtype=float32)

In [ ]:
x = np.array([1,2,3], dtype='U')

In [ ]:
x[0]+x[1]

'12'

# 배열 생성

In [ ]:
a = np.zeros((5,3), dtype='f')

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
f = np.ones_like(a, dtype='f')

In [ ]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
g = np.empty((4,3))

In [ ]:
g

array([[4.12328058e-316, 0.00000000e+000, 8.06809200e-321],
       [4.12429519e-316, 6.93454253e-310, 6.93454253e-310],
       [6.93454253e-310, 6.93454253e-310, 4.12327583e-316],
       [4.94065646e-324, 2.12199579e-314, 4.44659081e-323]])

In [ ]:
g = np.empty(a.shape)

In [ ]:
g

array([[ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312],
       [ 9.54898106e-313,  1.14587773e-312,  1.01855798e-312],
       [ 1.23075756e-312,  1.03977794e-312,  1.10343781e-312],
       [ 9.76118064e-313,  1.14587773e-312,  1.10343781e-312],
       [ 1.12465777e-312,  3.44981226e+175, -2.53481361e-170]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [ ]:
g.T

array([[ 3.63393267e-316,  9.54898106e-313,  1.23075756e-312,
         9.76118064e-313,  1.12465777e-312],
       [ 1.06099790e-312,  1.14587773e-312,  1.03977794e-312,
         1.14587773e-312,  3.44981226e+175],
       [ 1.01855798e-312,  1.01855798e-312,  1.10343781e-312,
         1.10343781e-312, -2.53481361e-170]])

# 배열의 크기 변경

In [ ]:
g. reshape(3,5)
g

array([[ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312],
       [ 9.54898106e-313,  1.14587773e-312,  1.01855798e-312],
       [ 1.23075756e-312,  1.03977794e-312,  1.10343781e-312],
       [ 9.76118064e-313,  1.14587773e-312,  1.10343781e-312],
       [ 1.12465777e-312,  3.44981226e+175, -2.53481361e-170]])

In [ ]:
g.flatten()

array([ 3.63393267e-316,  1.06099790e-312,  1.01855798e-312,
        9.54898106e-313,  1.14587773e-312,  1.01855798e-312,
        1.23075756e-312,  1.03977794e-312,  1.10343781e-312,
        9.76118064e-313,  1.14587773e-312,  1.10343781e-312,
        1.12465777e-312,  3.44981226e+175, -2.53481361e-170])

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# concatenate

In [ ]:
a1 = np.ones((2,3))

In [ ]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a2 = np.zeros((2,2))

In [ ]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
a2 = np.zeros((1,3))
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [ ]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
d = np.dstack([c1,c2])
d
d.shape

(3, 4, 2)

In [ ]:
c = np.stack([c1, c2])
c.shape

(2, 3, 4)

In [ ]:
c = np.stack([c1, c2], axis=1)
c.shape

(3, 2, 4)

In [ ]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# Grid point

In [ ]:
x = np.arange(3)
y = np.arange(5)

X, Y = np.meshgrid(x,y)
print(X)
print(Y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [ ]:
[list(zip(x,y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

# Vectorized operation

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,2,3,1])
a == b

array([False,  True,  True, False])

In [ ]:
a >= b

array([False,  True,  True,  True])

In [ ]:
c = np.array([1,2,3,4])
np.all(a==b)

False

In [ ]:
np.all(a==c)

True

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## broadcasting

In [ ]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])

In [ ]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
[range(10)[i:i+3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [ ]:
y = np.arange(5)[:,np.newaxis]

In [ ]:
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
x.sum()

45

In [ ]:
x.sum(axis=1)

array([ 3,  6,  9, 12, 15])

In [ ]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
x.argmin()

0

In [ ]:
np.any(x!=0)

True

In [ ]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
j=np.argsort(a)
print(j)

[[1 0 2 3]
 [0 3 2 1]
 [2 0 3 1]]


In [ ]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
j = np.argsort(a)



IndexError: ignored

In [ ]:
v = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
s = np.argsort(v[1,:])
s

array([0, 3, 1, 2])

In [ ]:
v[:,s]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# descriptive statistics

In [3]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [4]:
len(x)

26

In [5]:
np.mean(x)

4.8076923076923075

In [6]:
np.var(x)

115.23224852071006

In [7]:
np.std(x)

10.734628476137871

In [8]:
np.max(x)

23

In [9]:
np.min(x)

-24

In [10]:
np.median(x)

5.0

In [16]:
np.quantile(x,0.75)

10.0

# Random number

In [18]:
np.random.seed(0)
np.random.rand(5)


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [19]:
np.random.randn(5)

array([-0.84272405,  1.96992445,  1.26611853, -0.50587654,  2.54520078])

In [24]:
x = np.arange(5)
print(x)
np.random.shuffle(x)
x

[0 1 2 3 4]


array([0, 1, 4, 2, 3])

In [28]:
x = np.arange(20)
np.random.choice(x,10,True)

array([14, 15,  3, 15, 13, 16, 17,  5,  9,  3])

In [31]:
np.random.randint(10,size=5)

array([0, 5, 0, 1, 2])

In [32]:
np.random.randint(20,40,size=20)

array([24, 22, 36, 23, 22, 30, 33, 36, 27, 29, 20, 30, 38, 31, 22, 22, 23,
       23, 38, 34])

In [36]:
np.random.randint(0,2,size=10)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [39]:
x = np.random.randint(1,7,size=100)

In [40]:
np.mean(x)

3.55

In [53]:
x = 10000
y = np.random.randn(100)/100+1

In [54]:
y=np.cumprod(y)

In [55]:
x*y

array([10080.60823319, 10132.93716638, 10120.03951306, 10034.93159886,
        9985.22796041,  9971.54620057, 10070.0076903 ,  9997.64968208,
       10191.40763016, 10213.86860704, 10165.34303918, 10189.60303586,
       10230.93638984, 10261.59428386, 10332.51883622, 10135.59784773,
       10164.18472646,  9931.66477851,  9876.89421705,  9996.16963268,
        9881.03394417,  9896.36758914,  9833.82164974,  9655.16346597,
        9637.01032013,  9645.59368858,  9490.74391567,  9423.59542309,
        9221.0725139 ,  9232.71907458,  9228.69092229,  9322.15126129,
        9159.72795948,  9061.85861304,  9211.86403522,  9290.34285063,
        9417.71179417,  9443.52334369,  9481.6571436 ,  9383.04519248,
        9500.65085684,  9462.4368813 ,  9317.37625605,  9461.4457724 ,
        9473.22968565,  9492.79662718,  9406.8873354 ,  9468.45523666,
        9512.1361603 ,  9354.74918994,  9225.14567708,  9266.16359385,
        9187.701266  ,  9269.77282923,  9305.62471059,  9305.14693452,
      

In [56]:
x = np.array([1,2,3,4,2,3,])

In [57]:
np.bincount(x,minlength=6)

array([0, 1, 2, 2, 1, 0])

In [59]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4]), array([1, 2, 2, 1]))